set paste
set termguicolors
set background=dark
colorscheme NeoSolarized
let mapleader="\\"
set viminfo+=n$HOME/.config/nvim/.viminfo
set backup
set undofile
set backupdir=$HOME/.local/share/nvim/backup
set undodir=$HOME/.local/share/nvim/undo
set directory=$HOME/.local/share/nvim/swap
