#PATH+=":/home/gmend/.gem/ruby/2.5.0/bin"
#PATH+=":/home/gmend/.local/bin"
#export PATH
#if [[ -r ~/.zshrc ]]; then
#    . ~/.zshrc
#fi

# wayland support is still pretty bad
# export KITTY_ENABLE_WAYLAND=1

if [ -z "$DISPLAY" ] && [ -n "$XDG_VTNR" ] && [ "$XDG_VTNR" -eq 1 ]; 
then
    #eval $(ssh-agent)
    #startx
    keychain --quiet --dir "$XDG_CONFIG_HOME/keychain" --timeout 60
    sway # -d 2>> ~/sway.log
fi

export PATH="/home/gmend/.local/share/cargo/bin:$PATH"
