#PATH+=":/home/gmend/.gem/ruby/2.5.0/bin"
#PATH+=":/home/gmend/.local/bin"
#export PATH
#if [[ -r ~/.zshrc ]]; then
#    . ~/.zshrc
#fi

if [ -z "$DISPLAY" ] && [ -n "$XDG_VTNR" ] && [ "$XDG_VTNR" -eq 1 ]; 
then
    #eval $(ssh-agent)
    #startx
    keychain --quiet --dir "$XDG_CONFIG_HOME/keychain" --timeout 60
    sway
fi
