source /etc/profile.d/vte.sh

if [[ -r ~/.zshrc ]]; then
    . ~/.zshrc
fi

if [ -z "$DISPLAY" ] && [ -n "$XDG_VTNR" ] && [ "$XDG_VTNR" -eq 1 ]; 
then
    eval $(ssh-agent)
    #startx
    #startplasmacompositor
    sway
fi
