# we ran keychain in zprofile
source $HOME/.keychain/spectre-sh

#source zsh files
source $HOME/.dotfiles/zsh/completion.zsh
source $HOME/.dotfiles/zsh/keybindings.zsh
source $HOME/.dotfiles/zsh/termsupport.zsh
source $HOME/.dotfiles/zsh/environment.zsh
#source /usr/share/doc/pkgfile/command-not-found.zsh
# we can just use pikaur -Fs(x) and -Fl

### Functions ###
function match_filename() {
  find "$1" -iname "*$2*" -print
}
function match_contents() {
  grep -Ri "$1" -e "$2"
}
function matchrun_filename() {
  find "$1" -iname "*$2*" -print0 | xargs -0 ls -l
}
function matchrun_contents() {
  grep -Ri "$1" -e "$2" -lZ | xargs -0 "${@:3}"
}
function search() {
    grep --line-buffered --color=never -r "$1" * | fzf
}

# Evaluate dircolors
if [[ -f ~/.dircolors ]] ;
    then eval "$(dircolors -b ~/.dircolors)"
#elif [[ -f /etc/DIR_COLORS ]] ;
#    then eval $(dircolors -b /etc/DIR_COLORS)
fi

# Set up colored ls
ls --color -d . &>/dev/null && alias ls='ls --color'
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}

#ls after cd
auto-ls () { ls; }
#chpwd_functions=( auto-ls $chpwd_functions )
chpwd_functions=( auto-ls )

# load some plugins
if [[ -d $XDG_CONFIG_HOME/zsh/repos/ ]]
then
    source $XDG_CONFIG_HOME/zsh/repos/zsh-autosuggestions/zsh-autosuggestions.zsh
    source $XDG_CONFIG_HOME/zsh/repos/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
    source $XDG_CONFIG_HOME/zsh/repos/zsh-history-substring-search/zsh-history-substring-search.zsh
    fpath+=($XDG_CONFIG_HOME/zsh/fpath) #source spaceship prompt init
    fpath+=($XDG_CONFIG_HOME/zsh/repos/zsh-completions/src)
    export fpath
fi
autoload -U promptinit; promptinit
prompt spaceship

#Plugin Options
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=4'
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
#Theme options
#PURE_PROMPT_SYMBOL=❯
#SPACESHIP_TIME_SHOW=true
SPACESHIP_EXEC_TIME_ELAPSED=3
SPACESHIP_BATTERY_THRESHOLD=15
SPACESHIP_VI_MODE_SHOW=false
