# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Uncomment the following line to enable command auto-correction.
#ENABLE_CORRECTION="true"

# ssh
export SSH_KEY_PATH="~/.ssh/rsa_id"
added_keys=`ssh-add -l`

if [ ! $(echo $added_keys | grep -o -e id_rsa) ]; then
    ssh-add "$HOME/.ssh/id_rsa"
fi
#eval `keychain --eval id_rsa`

autoload -Uz compinit
compinit

source ~/.dotfiles/zsh/powerlevel9k.zsh

# Load zplug and plugins
if [[ ! -d "$HOME/.zplug" ]];then
    git clone https://github.com/b4b4r07/zplug ~/.zplug
fi
ZPLUG_HOME="$HOME/.zplug"
#If zplug is properly installed, load it
if [ -f $ZPLUG_HOME/init.zsh ]; then
    source "$ZPLUG_HOME/init.zsh"
fi
#Load plugins/themes/etc
zplug "zsh-users/zsh-syntax-highlighting"
zplug "zsh-users/zsh-autosuggestions"
#zplug "bhilburn/powerlevel9k", use:powerlevel9k.zsh-theme
#zplug "inimicus/z4rr3t", use:z4rr3t.zsh
zplug "glek/34ee8286eb9141056cd85a02bfd4fcd3", \
    from:gist, \
    as:theme, \
    use:blinks_custom.zsh-theme
zplug "zplug/zplug", hook-build:'zplug --self-manage'
#If zplug check gives output, ie, there are uninstalled plugins, install them
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi
zplug load #--verbose

# Aliases
alias l='ls -lah'
alias vim="vim --servername vim"
alias color="~/.dotfiles/changecolor.sh"

# Evaluate dircolors
if [[ -f ~/.dircolors ]] ;
    then eval "$(dircolors -b ~/.dircolors)"
elif [[ -f /etc/DIR_COLORS ]] ;
    then eval $(dircolors -b /etc/DIR_COLORS)
fi

# Set up colored ls
ls --color -d . &>/dev/null && alias ls='ls --color=tty'
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
#Ls after cd
auto-ls () { ls; }
chpwd_functions=( auto-ls $chpwd_functions )

#Misc options
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg-12'
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
DEFAULT_USER=gmend

#Hist options
if [ -z "$HISTFILE" ]; then
    HISTFILE=$HOME/.zsh_history
fi
HISTSIZE=1000 #We have plenty of memory, save our history
SAVEHIST=1000
setopt NO_HIST_BEEP #No annoying beeping
setopt INC_APPEND_HISTORY SHARE_HISTORY HIST_IGNORE_DUPS HIST_EXPIRE_DUPS_FIRST

source ~/.dotfiles/zsh/completion.zsh
source ~/.dotfiles/zsh/keybindings.zsh
source ~/.dotfiles/zsh/termsupport.zsh
